const fs = require('fs');

const lines = [
  "import React, { Suspense } from 'react';",
  "import { BrowserRouter, Routes, Route, Navigate, useLocation } from 'react-router-dom';",
  "import { AppLayout } from '@/components/layout/AppLayout';",
  "import { ToastProvider } from '@/components/ui/toast';",
  "import { ThemeProvider } from '@/context/ThemeContext';",
  "import LoginPage from '@/pages/Auth/Login';",
  "import { AuthProvider, useAuth } from '@/context/AuthContext';",
  "import { OfflineDetector } from '@/components/pwa/OfflineDetector';",
  "import { SSEProvider } from '@/components/SSEProvider';",
  "const Dashboard = React.lazy(() => import('@/pages/Dashboard'));",
  "const CustomersPage = React.lazy(() => import('@/pages/Customers'));",
  "const CustomerDetailsPage = React.lazy(() => import('@/pages/Customers/CustomerDetails'));",
  "const BillsPage = React.lazy(() => import('@/pages/Bills'));",
  "const BillDetailsPage = React.lazy(() => import('@/pages/Bills/BillDetails'));",
  "const PaymentsPage = React.lazy(() => import('@/pages/Payments'));",
  "const ReportsPage = React.lazy(() => import('@/pages/Reports'));",
  "const SettingsPage = React.lazy(() => import('@/pages/Settings'));",
  "const DailyBillsPage = React.lazy(() => import('@/pages/DailyBills'));",
  "const AUTH_BYPASS = import.meta.env.VITE_AUTH_BYPASS === 'true';",
  "function ProtectedRoute({ children }: { children: React.ReactNode }) {",
  "  const { isAuthenticated, loading } = useAuth();",
  "  const location = useLocation();",
  "  if (AUTH_BYPASS) { return <>{children}</>; }",
  "  if (loading) {",
  "    return (",
  "      <div className=\"min-h-screen flex items-center justify-center bg-slate-50\">",
  "        <div className=\"flex flex-col items-center gap-3\">",
  "          <div className=\"h-8 w-8 border-2 border-indigo-600 border-t-transparent rounded-full animate-spin\" />",
  "          <span className=\"text-sm text-gray-500\">Loading...</span>",
  "        </div>",
  "      </div>",
  "    );",
  "  }",
  "  if (!isAuthenticated) { return <Navigate to=\"/login\" state={{ from: location }} replace />; }",
  "  return <>{children}</>;",
  "}",
  "function AuthRoute({ element }: { element: React.ReactElement }) {",
  "  if (AUTH_BYPASS) { return <Navigate to=\"/\" replace />; }",
  "  return element;",
  "}",
  "function PageFallback() {",
  "  return (",
  "    <div className=\"flex items-center justify-center h-full w-full py-12\">",
  "      <div className=\"h-8 w-8 border-2 border-indigo-600 border-t-transparent rounded-full animate-spin\"></div>",
  "    </div>",
  "  );",
  "}",
  "function App() {",
  "  return (",
  "    <ThemeProvider>",
  "      <AuthProvider>",
  "        <ToastProvider>",
  "          <OfflineDetector />",
  "          <BrowserRouter>",
  "            <Routes>",
  "              <Route path=\"/login\" element={<AuthRoute element={<LoginPage />} />} />",
  "              <Route path=\"/\" element={<ProtectedRoute><SSEProvider><AppLayout /></SSEProvider></ProtectedRoute>}>",
  "                <Route index element={<Suspense fallback={<PageFallback />}><Dashboard /></Suspense>} />",
  "                <Route path=\"customers\" element={<Suspense fallback={<PageFallback />}><CustomersPage /></Suspense>} />",
  "                <Route path=\"customers/:id\" element={<Suspense fallback={<PageFallback />}><CustomerDetailsPage /></Suspense>} />",
  "                <Route path=\"bills\" element={<Suspense fallback={<PageFallback />}><BillsPage /></Suspense>} />",
  "                <Route path=\"bills/:id\" element={<Suspense fallback={<PageFallback />}><BillDetailsPage /></Suspense>} />",
  "                <Route path=\"daily-bills\" element={<Suspense fallback={<PageFallback />}><DailyBillsPage /></Suspense>} />",
  "                <Route path=\"payments\" element={<Suspense fallback={<PageFallback />}><PaymentsPage /></Suspense>} />",
  "                <Route path=\"reports\" element={<Suspense fallback={<PageFallback />}><ReportsPage /></Suspense>} />",
  "                <Route path=\"settings\" element={<Suspense fallback={<PageFallback />}><SettingsPage /></Suspense>} />",
  "              </Route>",
  "              <Route path=\"*\" element={<Navigate to=\"/\" replace />} />",
  "            </Routes>",
  "          </BrowserRouter>",
  "        </ToastProvider>",
  "      </AuthProvider>",
  "    </ThemeProvider>",
  "  );",
  "}",
  "export default App;"
];

fs.writeFileSync('src/App.tsx', lines.join('\\n'), 'utf8');
